config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :views
  resources :destinations
  root to: 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  
  
end

app/models/destination.rb
class Destination < ActiveRecord::Base
    has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    if params[:country] == nil
      @destinations = Destination.all
    else
      @destinations = Destination.where(country:params[:country].titleize)
    end
    
    @my_countries = Destination.select(:country).order(:country).distinct
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
    @destination = Destination.find(params[:id])
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :img, :population)
    end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for @destination, html: { multipart: true } do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :population %><br>
    <%= f.text_field :population, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :img %><br>
    <%= f.file_field :img %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </p>
<% end %>

<% if alert != nil %>
  <p id="alert" class="alert alert-danger" role="alert">
    <%= alert %>
  </p>
<% end %>

<ul class="nav nav-pills" role="tablist">
  <li><%= link_to "All", destinations_path %></li>
  <% @my_countries.each do |c| %>
  <li><%= link_to "#{c.country}", controller: "destinations", country: "#{c.country}" %></li>
  <% end %>
</ul>

<h1>My Destination Wish List</h1>

<div class="row">
  <% @destinations.each do |destination| %>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= image_tag destination.img.url(:medium), class: "img-responsive center-block" %>
        <h2><%= destination.city %></h2>
        <h4><%= destination.population %> Citizens</h4>
        <h3><%= destination.country %></h3>
        <p><%= destination.description %></p>
        
        <div class="btn-group">
          <%= link_to 'Show', destination, class: 'btn btn-default'%>
          <% if user_signed_in? %>
            <%= link_to 'Edit', edit_destination_path(destination), class: 'btn btn-default'%>
            <%= link_to 'Destroy', destination, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default'%>
          <% end %>
        </div>
        
      </div>      
    </div>    
  </div>
  <% end %>
</div>

<% if user_signed_in? %>
  <%= link_to 'New Destination', new_destination_path, class: 'btn btn-primary' %>
<% end %>  

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </p>
<% end %>

<% if alert != nil %>
  <p id="alert" class="alert alert-danger" role="alert">
    <%= alert %>
  </p>
<% end %>

<%= image_tag @destination.img.url(:medium) %>
<h1><%= @destination.city %>, <%= @destination.country %></h1>
<p><%= @destination.population %> Citizens</p>
<p><%= @destination.description %></p>
<div class="btn-group">
  <%= link_to 'Edit', edit_destination_path(@destination), class: 'btn btn-default' %>
  <%= link_to 'Back', destinations_path, class: 'btn btn-default' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Travel App</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Destinations", destinations_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign In', new_user_session_path  %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path  %></li>
          <% end %>  
      </ul>
      
      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>    




<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>